"""Per-page heading-candidate detection. This module builds and filters heading candidates from page blocks. It combines
numbering recognition, chapter/appendix keywords, local neighbor geometry,
font/style signals, cross-page rejection, and page-level candidate filtering
before handing candidates to outline assembly.
"""

import json
import math
import re
from pathlib import Path
from typing import Any, Optional

import regex as regex_module  # Unicode \p{...} property classes.

from ..labels import (
    CaptionEntry,
    advance_past_line,
    extract_structural_number,
    format_caption_label,
    is_uppercase_dominant,
    skip_bracketed_word,
    token_case_signal,
    trie_matches_all,
)
from ..model import (
    _UNICODE_WHITESPACE_CLASS,
    Block,
    CharStats,
    Line,
    _strip_diacritics,
    _trim_unicode_ws,
    alignment_code,
    avg_char_width,
    block_text,
    center_aligned,
    deaccented_text,
    dominant_font_size,
    dominant_style_of,
    first_span_of,
    heading_score,
    info_weight,
    is_caps_heavy,
    is_punct_category,
    is_upper_dominant,
    is_word_category,
    last_line_of,
    last_span,
    left_aligned,
    letter_count,
    magnitude_ratio,
    numbering_kind,
    numbering_text,
    numbering_value,
    punct_count,
    raw_text_of_line,
    right_aligned,
    same_x_extent,
    same_y_extent,
    style_key,
    to_number,
    x_aligned,
    x_centers_close,
    y_overlaps,
)
from ..outline_assembly import HeadingCandidate, OutlineNode
from ..tokens import (
    COMMA_CHARS,
    Token,
    TokenView,
    TrieConfig,
    build_trie,
    enumerate_tokens,
    first_anchor_span,
    first_token,
    is_char_token,
    is_trimmable_token,
    is_word_token,
    last_token,
    last_token_anchor,
    set_case_fold,
    strip_leading_if_in,
    strip_trailing_comma,
    strip_trie_match,
    token_numeric_value,
    tokenize_block,
    trie_full_match,
    trie_prefix_match,
    trim_trailing_punct,
    wrap_tokens,
)
from .candidates import (
    PageScanState,
    _di_count,
    _number_at_token_index,
    make_body_heading_candidate,
    make_heading_candidate,
    make_numbered_candidate,
    make_plain_candidate,
    push_candidate,
)
from .detectors import (
    classify_heading,
    detect_box_heading,
    detect_chapter_appendix,
    detect_labeled_heading,
    detect_numbered_heading,
    has_competing_labeled_heading,
    is_acceptable_heading,
    is_bibliography_entry,
    is_too_wide_for_heading,
    is_year_string,
    passes_neighbor_check,
    safe_column_index,
    try_classify_heading,
)
from .keyword_tables import (
    _DICT_PATH,
    _DICTS,
    ABSTRACT_KEYWORDS_SET,
    ABSTRACT_KEYWORDS_TRIE,
    APPENDIX_KEYWORDS_TRIE,
    APPENDIX_SECTION_TRIE,
    BOX_KEYWORD_TRIE,
    CHAPTER_WORDS_TRIE,
    DEAD_DIGIT_RE,
    ENGLISH_WORD_TO_NUMBER,
    EQUATION_KEYWORDS_TRIE,
    FORMULA_CHAR_WEIGHTS,
    INTRODUCTION_SECTION_TRIE,
    KEYWORDS_SECTION_TRIE,
    NUMBERED_PREFIX_RE,
    REFERENCES_SET,
    REFERENCES_TRIE,
    ROMAN_NUMERAL_MAP,
    SECTION_KEYWORDS_TRIE,
    _normalize_text_key,
)
from .neighbors import (
    BlockNeighborCache,
    PageNeighborMap,
    body_neighbor_above,
    closest_body_neighbor_above,
    compute_bucket_span,
    neighbor_above,
    neighbor_right,
    neighbor_right_peer,
)
from .page_scan import (
    DocCandidateCollector,
    build_doc_heading_candidates,
    filter_page_candidates,
    find_section_openers,
    scan_page_headings,
)
from .style_detectors import (
    detect_font_heading,
    detect_heading_with_body,
)
from .text_checks import (
    clamp,
    has_substantive_content,
    is_cover_page,
    is_equation_adjacent_line,
    is_heading_continuation,
    letter_to_ordinal,
    matches_abstract,
    matches_references,
    similar_style,
    token_text_of_block,
    token_to_number,
    vertically_close,
)

__all__ = [
    "SECTION_KEYWORDS_TRIE",
    "ABSTRACT_KEYWORDS_TRIE",
    "ABSTRACT_KEYWORDS_SET",
    "REFERENCES_TRIE",
    "REFERENCES_SET",
    "APPENDIX_SECTION_TRIE",
    "INTRODUCTION_SECTION_TRIE",
    "BOX_KEYWORD_TRIE",
    "KEYWORDS_SECTION_TRIE",
    "CHAPTER_WORDS_TRIE",
    "APPENDIX_KEYWORDS_TRIE",
    "ROMAN_NUMERAL_MAP",
    "ENGLISH_WORD_TO_NUMBER",
    "FORMULA_CHAR_WEIGHTS",
    "NUMBERED_PREFIX_RE",
    "DEAD_DIGIT_RE",
    "is_heading_continuation",
    "similar_style",
    "matches_abstract",
    "matches_references",
    "vertically_close",
    "is_equation_adjacent_line",
    "has_substantive_content",
    "is_cover_page",
    "token_to_number",
    "letter_to_ordinal",
    "BlockNeighborCache",
    "compute_bucket_span",
    "neighbor_above",
    "body_neighbor_above",
    "neighbor_right",
    "closest_body_neighbor_above",
    "PageNeighborMap",
    "PageScanState",
    "DocCandidateCollector",
    "filter_page_candidates",
    "classify_heading",
    "is_acceptable_heading",
    "try_classify_heading",
    "push_candidate",
    "detect_numbered_heading",
    "make_heading_candidate",
    "detect_labeled_heading",
    "make_body_heading_candidate",
    "detect_heading_with_body",
    "detect_chapter_appendix",
    "is_too_wide_for_heading",
    "passes_neighbor_check",
    "make_plain_candidate",
    "make_numbered_candidate",
    "has_competing_labeled_heading",
    "detect_font_heading",
    "scan_page_headings",
    "detect_box_heading",
    "build_doc_heading_candidates",
]
