"""YAML helpers for scaffolded apps."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, List, Optional

import yaml


def read_app_yaml(path: Path) -> Dict[str, Any]:
    with open(path, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f)
    if not isinstance(data, dict):
        raise ValueError(f"Invalid app.yaml at {path}")
    return data


def write_app_yaml(path: Path, data: Dict[str, Any]) -> None:
    with open(path, "w", encoding="utf-8") as f:
        yaml.safe_dump(
            data,
            f,
            default_flow_style=False,
            allow_unicode=True,
            sort_keys=False,
            width=120,
        )


def append_agent_to_app_yaml(
    app_yaml_path: Path,
    agent_ref: str,
    *,
    force: bool = False,
) -> None:
    """Append ``namespace/agent`` to ``agents:`` if missing."""
    data = read_app_yaml(app_yaml_path)
    agents = data.get("agents")
    if agents is None:
        agents = []
        data["agents"] = agents
    if not isinstance(agents, list):
        raise ValueError("app.yaml agents must be a list")

    if agent_ref in agents:
        if not force:
            raise ValueError(
                f"Agent {agent_ref!r} is already listed in app.yaml (use --force to continue)"
            )
        return

    agents.append(agent_ref)
    write_app_yaml(app_yaml_path, data)


def write_agent_yaml(
    path: Path,
    *,
    agent_ref: str,
    author: str,
    version: str,
    jvagent_version: str,
    alias: str,
    description: str,
    actions: List[Dict[str, Any]],
) -> None:
    doc: Dict[str, Any] = {
        "agent": agent_ref,
        "version": version,
        "author": author,
        "jvagent": jvagent_version,
        "context": {
            "alias": alias,
            "description": description,
            "enabled": True,
        },
        "actions": actions,
    }
    with open(path, "w", encoding="utf-8") as f:
        f.write("# Generated by jvagent scaffold — customize as needed.\n\n")
        yaml.safe_dump(
            doc,
            f,
            default_flow_style=False,
            allow_unicode=True,
            sort_keys=False,
            width=100,
        )


def apply_agent_placeholders(obj: Any, title: str, description: str) -> Any:
    """Replace scaffold tokens in nested structures."""
    if isinstance(obj, str):
        return obj.replace("__JVAGENT_SCAFFOLD_AGENT_TITLE__", title).replace(
            "__JVAGENT_SCAFFOLD_AGENT_DESCRIPTION__", description
        )
    if isinstance(obj, dict):
        return {
            k: apply_agent_placeholders(v, title, description) for k, v in obj.items()
        }
    if isinstance(obj, list):
        return [apply_agent_placeholders(i, title, description) for i in obj]
    return obj
